name: Publish

on:
  push:
    tags:
      - "*"

jobs:
  build:
    env:
      # Nuget package version taken from the tag itself
      version: ${{github.ref_name}}
    name: Publish NuGet Package
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: |
          8.0.x
          9.0.x
          10.0.x
    - name: Install Dependencies
      run: dotnet restore .\\src\\NLog.Loki.sln
    - name: Build
      run: dotnet build .\\src\\NLog.Loki.sln --configuration Release --no-restore
    - name: Publish
      id: publish
      uses: alirezanet/publish-nuget@v3.1.0
      with:
        PROJECT_FILE_PATH: ./src/NLog.Loki/NLog.Loki.csproj
        VERSION_STATIC: ${{env.version}}
        NUGET_KEY: ${{secrets.NUGET_KEY}}
        INCLUDE_SYMBOLS: true
        TAG_COMMIT: false
